import { v4 as uuid } from "uuid";
/**
 * Videos Database can be added here.
 * You can add videos of your wish with different attributes
 * */

export const videos = [
  {
    _id: uuid(),
    img: "./assets/comedy2.webp",
    title:
      "Friends: Phoebe, Chandler and Monica Babysit The Triplets (Season 6 Clip) | TBS",
    owner: "TBS",
    views: "176k",
    date: "Dec 4, 2021",
    categoryName: "Comedy",
  },
  {
    _id: uuid(),
    img: "./assets/comedy1.webp",
    title: "Friends Best Moments From Season 2",
    owner: "Clash World",
    views: "380k",
    date: "Mar 16, 2021",
    categoryName: "Comedy",
  },
  {
    _id: uuid(),
    img: "./assets/comedy3.webp",
    title:
      "Friends: The Friends Meet Rachel’s Spoiled Sister, Jill (Season 6 Clip) | TBS",
    owner: "TBS",
    views: "113k",
    date: "Feb 28, 2022",
    categoryName: "Comedy",
  },
  {
    _id: uuid(),
    img: "./assets/comedy4.webp",
    title:
      "Friends: Monica Is Jealous Phoebe Picks Rachel To Date (Season 6 Clip) | TBS",
    owner: "TBS",
    views: "776k",
    date: "Feb 14, 2022",
    categoryName: "Comedy",
  },
  {
    _id: uuid(),
    img: "./assets/comedy5.webp",
    title: "Friends: Ross' Fake British Accent (Season 6 Clip) | TBS",
    owner: "TBS",
    views: "768k",
    date: "Feb 18, 2022",
    categoryName: "Comedy",
  },
  {
    _id: uuid(),
    img: "./assets/action1.jpg",
    title: "Best Of Spider Man Saves",
    owner: "MovieZ4U",
    views: "17.5M",
    date: "Oct 19, 2015",
    categoryName: "Action",
  },
  {
    _id: uuid(),
    img: "./assets/action2.jpg",
    title: "SPIDER-MAN Vs VENOM Best Action Scenes 4K ᴴᴰ",
    owner: "ONE Media",
    views: "8.5M",
    date: "Dec 30, 2021",
    categoryName: "Action",
  },
  {
    _id: uuid(),
    img: "./assets/action3.jpg",
    title:
      "Spider-Man vs Sandman - Subway Fight Scene - Spider-Man 3 (2007) Movie CLIP HD",
    owner: "TopMovieClips",
    views: "66M",
    date: "Jul 18, 2017",
    categoryName: "Action",
  },
  {
    _id: uuid(),
    img: "./assets/action4.jpg",
    title: "Avengers: Endgame | Final Battle #1 | 4K 60fps",
    owner: "The Entertainment Analyst",
    views: "780k",
    date: "Oct 17, 2021",
    categoryName: "Action",
  },
  {
    _id: uuid(),
    img: "./assets/action5.jpg",
    title:
      "Captain America Avengers Assemble Scene - Portal Scene - Avengers : Endgame (2019) Scene",
    owner: "BestScene",
    views: "15M",
    date: "Nov 8, 2020",
    categoryName: "Action",
  },

  {
    _id: uuid(),
    img: "./assets/horror2.jpg",
    title:
      "The Little Hours FULL MOVIE 2017 English Sub || Alison Brie, Dave Franco, Kate Micucci",
    owner: "は Wedang Tuak",
    views: "1k",
    date: "Mar 23, 2022",
    categoryName: "Horror",
  },
  {
    _id: uuid(),
    img: "./assets/horror3.jpg",
    title: "The Nun: Escape the Abbey 360",
    owner: "Warner Bros. Pictures",
    views: "5.9M",
    date: "Aug 22, 2018",
    categoryName: "Horror",
  },
  {
    _id: uuid(),
    img: "./assets/horror4.jpg",
    title: "The Woman in Black (1989)",
    owner: "Rock n Roll Martian",
    views: "15k",
    date: "Oct 24, 2021",
    categoryName: "Horror",
  },
  {
    _id: uuid(),
    img: "./assets/thriller1.jpg",
    title: "Eleven & Mike's Cutest Moments | Stranger Things S1-3",
    owner: "Still Watching Netflix",
    views: "8.9M",
    date: "Jul 10, 2019",
    categoryName: "Thriler",
  },
  {
    _id: uuid(),
    img: "./assets/thriller2.jpg",
    title: "Stranger Things 2 | Official Final Trailer | Netflix",
    owner: "Netflix",
    views: "24M",
    date: "Oct 13, 2017",
    categoryName: "Thriler",
  },
  {
    _id: uuid(),
    img: "./assets/Thriller3.jpg",
    title: "The 11 Spookiest Monster Moments | Stranger Things | Netflix",
    owner: "Stranger Things",
    views: "10.9M",
    date: "Oct 15, 2019",
    categoryName: "Thriler",
  },
  {
    _id: uuid(),
    img: "./assets/Thriller4.jpg",
    title: "Legendary Dragon Scene Game of Thrones Season 5 (HD)",
    owner: "Blazor26",
    views: "10.7M",
    date: "Jun 8, 2015",
    categoryName: "Thriler",
  },
  {
    _id: uuid(),
    img: "./assets/Thriller5.jpg",
    title:
      "Epic Dragon Scene Game of Thrones Season 3 Daenerys Targaryen Rise to Power (Part 1) (HD)",
    owner: "Khaleesi",
    views: "20M",
    date: "Oct 19, 2021",
    categoryName: "Thriler",
  },
];
